name: Deploy to PythonAnywhere
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Django
        run: pip install django
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to PythonAnywhere
        uses: docker://pythonanywhere/pythonanywhere-deployment-action:v1
        with:
          api_token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          pythonanywhere_username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          local_project_path: '.'  # Adjust if your project is in a subdirectory
          remote_working_directory: '/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/Django-Deployment'  
          remote_wsgi_file_path: '/var/www/${{ secrets.PYTHONANYWHERE_USERNAME }}_pythonanywhere_com_wsgi.py'  
