name: Deploy to PythonAnywhere
on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to PythonAnywhere
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.PYTHONANYWHERE_HOST }}
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          password: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          port: 22
          script: |
            cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/your-project-directory
            git pull
            workon your-virtualenv-name
            python manage.py migrate
            python manage.py collectstatic --noinput
            # Restart your web app
            touch /var/www/${{ secrets.PYTHONANYWHERE_USERNAME }}_pythonanywhere_com_wsgi.py